/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.time.Month;
import java.time.temporal.ChronoUnit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import clases.*;


/**
 *
 * @author Keloc
 */
public class HospitalInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form BibliotecaInterfaz
     */

    private Image principalImage = new ImageIcon("src/main/resources/principalImg.png").getImage();
    private Image prestamoImage = new ImageIcon("src/main/resources/prestamoImg.png").getImage();
    private Image devolucionImage = new ImageIcon("src/main/resources/devolucionImg.png").getImage();
    private Image miembrosImage = new ImageIcon("src/main/resources/miembrosImg.png").getImage();
    private Image catalogoImage = new ImageIcon("src/main/resources/catalogoImg.png").getImage();
    private Image logsImage = new ImageIcon("src/main/resources/logsImg.png").getImage();
    private Image logoImage = new ImageIcon("src/main/resources/alejandria.jpg").getImage();
    public HospitalInterfaz() {
        initComponents();
        
        initStyles();
        initContent();
   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuOpciones = new javax.swing.JPanel();
        contenedorOpt = new javax.swing.JPanel();
        principalOptP = new javax.swing.JPanel();
        principalL = new javax.swing.JLabel();
        prestamosOptP = new javax.swing.JPanel();
        prestamosL = new javax.swing.JLabel();
        devolucionesOptP = new javax.swing.JPanel();
        devolucionesL = new javax.swing.JLabel();
        miembrosOptP = new javax.swing.JPanel();
        miembrosL = new javax.swing.JLabel();
        catalogoOptP = new javax.swing.JPanel();
        catalogoL = new javax.swing.JLabel();
        logsOptP = new javax.swing.JPanel();
        logsL = new javax.swing.JLabel();
        barraP = new javax.swing.JPanel();
        textoL1 = new javax.swing.JLabel();
        contentP = new javax.swing.JPanel();
        textoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(800, 500));
        bg.setPreferredSize(new java.awt.Dimension(800, 500));

        menuPanel.setBackground(new java.awt.Color(204, 204, 204));
        menuPanel.setMinimumSize(new java.awt.Dimension(175, 500));
        menuPanel.setPreferredSize(new java.awt.Dimension(187, 500));

        menuOpciones.setBackground(new java.awt.Color(122, 218, 245));
        menuOpciones.setPreferredSize(new java.awt.Dimension(175, 500));

        contenedorOpt.setBackground(new java.awt.Color(189, 238, 252));
        contenedorOpt.setMaximumSize(new java.awt.Dimension(350, 600));
        contenedorOpt.setMinimumSize(new java.awt.Dimension(175, 300));
        contenedorOpt.setPreferredSize(new java.awt.Dimension(185, 300));
        contenedorOpt.setLayout(new javax.swing.BoxLayout(contenedorOpt, javax.swing.BoxLayout.PAGE_AXIS));

        principalOptP.setBackground(new java.awt.Color(189, 238, 252));
        principalOptP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        principalOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        principalOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        principalOptP.setPreferredSize(new java.awt.Dimension(175, 50));
        principalOptP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalOptPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                principalOptPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                principalOptPMouseExited(evt);
            }
        });

        principalL.setBackground(new java.awt.Color(255, 255, 255));
        principalL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        principalL.setForeground(new java.awt.Color(88, 135, 237));
        principalL.setText("Principal");
        principalL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                principalLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                principalLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout principalOptPLayout = new javax.swing.GroupLayout(principalOptP);
        principalOptP.setLayout(principalOptPLayout);
        principalOptPLayout.setHorizontalGroup(
            principalOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, principalOptPLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(principalL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        principalOptPLayout.setVerticalGroup(
            principalOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalOptPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(principalL)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        contenedorOpt.add(principalOptP);

        prestamosOptP.setBackground(new java.awt.Color(189, 238, 252));
        prestamosOptP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prestamosOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        prestamosOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        prestamosOptP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prestamosOptPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prestamosOptPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prestamosOptPMouseExited(evt);
            }
        });

        prestamosL.setBackground(new java.awt.Color(255, 255, 255));
        prestamosL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        prestamosL.setForeground(new java.awt.Color(88, 135, 237));
        prestamosL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prestamosL.setText("Iniciar Sesión");
        prestamosL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prestamosLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                prestamosLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                prestamosLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout prestamosOptPLayout = new javax.swing.GroupLayout(prestamosOptP);
        prestamosOptP.setLayout(prestamosOptPLayout);
        prestamosOptPLayout.setHorizontalGroup(
            prestamosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prestamosOptPLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(prestamosL, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(4, Short.MAX_VALUE))
        );
        prestamosOptPLayout.setVerticalGroup(
            prestamosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prestamosOptPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(prestamosL)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenedorOpt.add(prestamosOptP);

        devolucionesOptP.setBackground(new java.awt.Color(189, 238, 252));
        devolucionesOptP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devolucionesOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        devolucionesOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        devolucionesOptP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devolucionesOptPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                devolucionesOptPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                devolucionesOptPMouseExited(evt);
            }
        });

        devolucionesL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        devolucionesL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        devolucionesL.setText("Expedientes");
        devolucionesL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devolucionesLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                devolucionesLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                devolucionesLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout devolucionesOptPLayout = new javax.swing.GroupLayout(devolucionesOptP);
        devolucionesOptP.setLayout(devolucionesOptPLayout);
        devolucionesOptPLayout.setHorizontalGroup(
            devolucionesOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devolucionesOptPLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(devolucionesL, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        devolucionesOptPLayout.setVerticalGroup(
            devolucionesOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devolucionesOptPLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(devolucionesL)
                .addGap(15, 15, 15))
        );

        contenedorOpt.add(devolucionesOptP);

        miembrosOptP.setBackground(new java.awt.Color(189, 238, 252));
        miembrosOptP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miembrosOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        miembrosOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        miembrosOptP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miembrosOptPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miembrosOptPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miembrosOptPMouseExited(evt);
            }
        });

        miembrosL.setBackground(new java.awt.Color(0, 0, 0));
        miembrosL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        miembrosL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miembrosL.setText("Recetas");
        miembrosL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miembrosLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                miembrosLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                miembrosLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout miembrosOptPLayout = new javax.swing.GroupLayout(miembrosOptP);
        miembrosOptP.setLayout(miembrosOptPLayout);
        miembrosOptPLayout.setHorizontalGroup(
            miembrosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miembrosOptPLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(miembrosL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        miembrosOptPLayout.setVerticalGroup(
            miembrosOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miembrosOptPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miembrosL)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        contenedorOpt.add(miembrosOptP);

        catalogoOptP.setBackground(new java.awt.Color(189, 238, 252));
        catalogoOptP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catalogoOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        catalogoOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        catalogoOptP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catalogoOptPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catalogoOptPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catalogoOptPMouseExited(evt);
            }
        });

        catalogoL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        catalogoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catalogoL.setText("Citas");
        catalogoL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catalogoLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catalogoLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catalogoLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout catalogoOptPLayout = new javax.swing.GroupLayout(catalogoOptP);
        catalogoOptP.setLayout(catalogoOptPLayout);
        catalogoOptPLayout.setHorizontalGroup(
            catalogoOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoOptPLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(catalogoL, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        catalogoOptPLayout.setVerticalGroup(
            catalogoOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoOptPLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(catalogoL)
                .addGap(15, 15, 15))
        );

        contenedorOpt.add(catalogoOptP);

        logsOptP.setBackground(new java.awt.Color(189, 238, 252));
        logsOptP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logsOptP.setMaximumSize(new java.awt.Dimension(350, 100));
        logsOptP.setMinimumSize(new java.awt.Dimension(175, 50));
        logsOptP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logsOptPMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logsOptPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logsOptPMouseExited(evt);
            }
        });

        logsL.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        logsL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logsL.setText("Pacientes");

        javax.swing.GroupLayout logsOptPLayout = new javax.swing.GroupLayout(logsOptP);
        logsOptP.setLayout(logsOptPLayout);
        logsOptPLayout.setHorizontalGroup(
            logsOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logsOptPLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(logsL, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        logsOptPLayout.setVerticalGroup(
            logsOptPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logsOptPLayout.createSequentialGroup()
                .addComponent(logsL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        contenedorOpt.add(logsOptP);

        javax.swing.GroupLayout menuOpcionesLayout = new javax.swing.GroupLayout(menuOpciones);
        menuOpciones.setLayout(menuOpcionesLayout);
        menuOpcionesLayout.setHorizontalGroup(
            menuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOpcionesLayout.createSequentialGroup()
                .addComponent(contenedorOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        menuOpcionesLayout.setVerticalGroup(
            menuOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuOpcionesLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(contenedorOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuOpciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(menuOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        barraP.setBackground(new java.awt.Color(122, 218, 245));

        textoL1.setBackground(new java.awt.Color(88, 135, 237));
        textoL1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        textoL1.setForeground(new java.awt.Color(88, 135, 237));
        textoL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoL1.setText("MEDBAY SOFTWARE");

        javax.swing.GroupLayout barraPLayout = new javax.swing.GroupLayout(barraP);
        barraP.setLayout(barraPLayout);
        barraPLayout.setHorizontalGroup(
            barraPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoL1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        barraPLayout.setVerticalGroup(
            barraPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraPLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(textoL1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        contentP.setBackground(new java.awt.Color(255, 255, 255));
        contentP.setMinimumSize(new java.awt.Dimension(0, 0));
        contentP.setPreferredSize(new java.awt.Dimension(605, 360));
        contentP.setLayout(new java.awt.BorderLayout());

        textoL.setBackground(new java.awt.Color(88, 135, 237));
        textoL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        textoL.setForeground(new java.awt.Color(88, 135, 237));
        textoL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoL.setText("Simplificando procesos, salvando vidas");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contentP, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoL, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(barraP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textoL)
                .addGap(18, 18, 18)
                .addComponent(barraP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contentP, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void prestamosOptPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosOptPMouseEntered
        prestamosOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_prestamosOptPMouseEntered

    private void devolucionesOptPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucionesOptPMouseEntered
        devolucionesOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_devolucionesOptPMouseEntered

    private void miembrosOptPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miembrosOptPMouseEntered
        miembrosOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_miembrosOptPMouseEntered

    private void prestamosOptPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosOptPMouseExited
        prestamosOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_prestamosOptPMouseExited

    private void devolucionesOptPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucionesOptPMouseExited
        devolucionesOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_devolucionesOptPMouseExited

    private void miembrosOptPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miembrosOptPMouseExited
        miembrosOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_miembrosOptPMouseExited

    private void logsOptPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsOptPMouseEntered
        logsOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_logsOptPMouseEntered

    private void logsOptPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsOptPMouseExited
        logsOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_logsOptPMouseExited

    private void catalogoOptPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoOptPMouseExited
        catalogoOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_catalogoOptPMouseExited

    private void catalogoOptPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoOptPMouseEntered
        catalogoOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_catalogoOptPMouseEntered

    private void prestamosOptPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosOptPMouseClicked
       

    }//GEN-LAST:event_prestamosOptPMouseClicked

    private void devolucionesOptPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucionesOptPMouseClicked
  
    }//GEN-LAST:event_devolucionesOptPMouseClicked

    private void miembrosOptPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miembrosOptPMouseClicked

    }//GEN-LAST:event_miembrosOptPMouseClicked

    private void catalogoOptPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoOptPMouseClicked

    }//GEN-LAST:event_catalogoOptPMouseClicked

    private void logsOptPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logsOptPMouseClicked

    }//GEN-LAST:event_logsOptPMouseClicked

    private void prestamosLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosLMouseClicked

    }//GEN-LAST:event_prestamosLMouseClicked

    private void devolucionesLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucionesLMouseClicked

    }//GEN-LAST:event_devolucionesLMouseClicked

    private void miembrosLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miembrosLMouseClicked

    }//GEN-LAST:event_miembrosLMouseClicked

    private void catalogoLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoLMouseClicked

    }//GEN-LAST:event_catalogoLMouseClicked

    private void catalogoLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoLMouseEntered
        catalogoOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_catalogoLMouseEntered

    private void prestamosLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosLMouseEntered
        prestamosOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_prestamosLMouseEntered

    private void devolucionesLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucionesLMouseEntered
        devolucionesOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_devolucionesLMouseEntered

    private void miembrosLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miembrosLMouseEntered
        miembrosOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_miembrosLMouseEntered

    private void devolucionesLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devolucionesLMouseExited
        devolucionesOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_devolucionesLMouseExited

    private void prestamosLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prestamosLMouseExited
        prestamosOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_prestamosLMouseExited

    private void miembrosLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miembrosLMouseExited
        miembrosOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_miembrosLMouseExited

    private void catalogoLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoLMouseExited
        catalogoOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_catalogoLMouseExited

    private void principalOptPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalOptPMouseExited
        principalOptP.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_principalOptPMouseExited

    private void principalOptPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalOptPMouseEntered
        principalOptP.setBackground(new Color(153, 204, 255));
    }//GEN-LAST:event_principalOptPMouseEntered

    private void principalOptPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalOptPMouseClicked
        initContent();
    }//GEN-LAST:event_principalOptPMouseClicked

    private void principalLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalLMouseExited
        principalOptP.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_principalLMouseExited

    private void principalLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalLMouseEntered
        principalOptP.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_principalLMouseEntered

    private void principalLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalLMouseClicked
        initContent();
    }//GEN-LAST:event_principalLMouseClicked

    private ImageIcon resizeImage(Image image, JLabel label){
        ImageIcon img = new ImageIcon(image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
        return img;
    }
    
    private void initStyles(){
        principalL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        prestamosL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        devolucionesL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        miembrosL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        catalogoL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        logsL.putClientProperty( "FlatLaf.style", "font: large $large.font" );
        textoL.putClientProperty( "FlatLaf.styleClass",  "h4");
        textoL.setFont(textoL.getFont().deriveFont(Font.ITALIC));
    }
    
    private void initContent(){
        changeContent(new Principal());
    }
    
    private void changeContent(JPanel panel){
        panel.setSize(contentP.getWidth(), contentP.getHeight());
        panel.setLocation(0,0);
        contentP.removeAll();
        contentP.add(panel, BorderLayout.CENTER);
        contentP.revalidate();
        contentP.repaint();
    }
    

    
    
   
    
    
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //Ficheros

        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HospitalInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HospitalInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HospitalInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HospitalInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HospitalInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraP;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel catalogoL;
    private javax.swing.JPanel catalogoOptP;
    private javax.swing.JPanel contenedorOpt;
    private javax.swing.JPanel contentP;
    private javax.swing.JLabel devolucionesL;
    private javax.swing.JPanel devolucionesOptP;
    private javax.swing.JLabel logsL;
    private javax.swing.JPanel logsOptP;
    private javax.swing.JPanel menuOpciones;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel miembrosL;
    private javax.swing.JPanel miembrosOptP;
    private javax.swing.JLabel prestamosL;
    private javax.swing.JPanel prestamosOptP;
    private javax.swing.JLabel principalL;
    private javax.swing.JPanel principalOptP;
    private javax.swing.JLabel textoL;
    private javax.swing.JLabel textoL1;
    // End of variables declaration//GEN-END:variables
}
