/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import clases.Auth;
import clases.Usuario;
import java.awt.Window;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Keloc
 */
public class LoginPanel extends javax.swing.JPanel {

    private HospitalInterfaz mainInterface;
    
    public LoginPanel(HospitalInterfaz mainInterface) {
        this.mainInterface = mainInterface;
        initComponents();
        errorTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        nombreUsuarioTF = new javax.swing.JTextField();
        iniciarSesionBtn = new javax.swing.JButton();
        errorTF = new javax.swing.JLabel();
        contraPF = new javax.swing.JPasswordField();
        togglePassBtn = new javax.swing.JToggleButton();

        nombreUsuarioTF.setText("Nombre de Usuario");
        nombreUsuarioTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioTFActionPerformed(evt);
            }
        });

        iniciarSesionBtn.setText("Iniciar Sesion");
        iniciarSesionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarSesionBtnActionPerformed(evt);
            }
        });

        errorTF.setForeground(new java.awt.Color(255, 51, 51));
        errorTF.setText("aparecerá si sale error");
        errorTF.setEnabled(false);

        contraPF.setText("Contraseña");

        togglePassBtn.setText("Mostrar");
        togglePassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreUsuarioTF)
                    .addComponent(contraPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgPanelLayout.createSequentialGroup()
                        .addComponent(errorTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(togglePassBtn)))
                .addGap(107, 107, 107))
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(iniciarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(nombreUsuarioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(contraPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorTF)
                    .addComponent(togglePassBtn))
                .addGap(22, 22, 22)
                .addComponent(iniciarSesionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarSesionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarSesionBtnActionPerformed
        String nombreUsuario = nombreUsuarioTF.getText();
        String contrasena = new String(contraPF.getPassword());
        try {
            Usuario usuario = Auth.iniciarSesion(nombreUsuario, contrasena);
            mainInterface.setCurrUser(usuario);
            mainInterface.initContent();
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_iniciarSesionBtnActionPerformed

    private void nombreUsuarioTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioTFActionPerformed

    private void togglePassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePassBtnActionPerformed
        if (togglePassBtn.isSelected()) {
            contraPF.setEchoChar((char) 0);
            togglePassBtn.setText("Ocultar");
        } else {
            contraPF.setEchoChar('•');
            togglePassBtn.setText("Mostrar");
        }
    }//GEN-LAST:event_togglePassBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JPasswordField contraPF;
    private javax.swing.JLabel errorTF;
    private javax.swing.JButton iniciarSesionBtn;
    private javax.swing.JTextField nombreUsuarioTF;
    private javax.swing.JToggleButton togglePassBtn;
    // End of variables declaration//GEN-END:variables
}
