/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import baseDeDatos.ExpControl;
import baseDeDatos.PacienteControl;
import clases.Expediente;
import clases.Paciente;
import clases.RecepcionistaPersonal;
import clases.Registro;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Keloc
 */
public class PacientesPanel extends javax.swing.JPanel {

    /**
     * Creates new form PacientesPanel
     */
    
    private HospitalInterfaz mainFrame;
    public PacientesPanel(HospitalInterfaz hi) {
        this.mainFrame = hi;
        initComponents();
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedasBG = new javax.swing.ButtonGroup();
        addEditPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addTel = new javax.swing.JTextField();
        razonVL = new javax.swing.JLabel();
        addRazon = new javax.swing.JTextField();
        addBuscarBtn = new javax.swing.JButton();
        consultarPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        consulNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        consulEdad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        consulTel = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVisitas = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistros = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        buscarBtn = new javax.swing.JButton();
        consultBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        listadoBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        idRB = new javax.swing.JRadioButton();
        nomRB = new javax.swing.JRadioButton();
        reloadBtn = new javax.swing.JButton();

        jLabel2.setText("Nombre:");

        jLabel3.setText("Edad:");

        jLabel4.setText("Telefono:");

        razonVL.setText("Razón de Visita:");

        addBuscarBtn.setText("Buscar");

        javax.swing.GroupLayout addEditPanelLayout = new javax.swing.GroupLayout(addEditPanel);
        addEditPanel.setLayout(addEditPanelLayout);
        addEditPanelLayout.setHorizontalGroup(
            addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEditPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(addNom, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addBuscarBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addEditPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(addEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addTel))
                    .addGroup(addEditPanelLayout.createSequentialGroup()
                        .addComponent(razonVL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addRazon)))
                .addContainerGap())
        );
        addEditPanelLayout.setVerticalGroup(
            addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBuscarBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(razonVL)
                    .addComponent(addRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel7.setText("Nombre:");

        consulNom.setEditable(false);

        jLabel8.setText("Edad:");

        consulEdad.setEditable(false);

        jLabel9.setText("Telefono:");

        consulTel.setEditable(false);

        tablaVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Razon de Visita", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaVisitas);

        jLabel10.setText("Visitas");

        javax.swing.GroupLayout consultarPanelLayout = new javax.swing.GroupLayout(consultarPanel);
        consultarPanel.setLayout(consultarPanelLayout);
        consultarPanelLayout.setHorizontalGroup(
            consultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(consultarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(consulNom))
                    .addGroup(consultarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(consulEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consulTel, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                    .addGroup(consultarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        consultarPanelLayout.setVerticalGroup(
            consultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(consulNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(consultarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(consulEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(consulTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tablaRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistros);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pacientes");

        buscarBtn.setText("Buscar");

        consultBtn.setText("Consultar");
        consultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Editar");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        addBtn.setText("Añadir");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        listadoBtn.setText("Listado");
        listadoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listadoBtnActionPerformed(evt);
            }
        });

        busquedasBG.add(idRB);
        idRB.setText("Id Paciente");

        busquedasBG.add(nomRB);
        nomRB.setText("Nombre Paciente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomRB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idRB)
                    .addComponent(nomRB))
                .addContainerGap())
        );

        reloadBtn.setText("Reiniciar");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(consultBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(listadoBtn)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reloadBtn)
                                .addGap(54, 54, 54)))
                        .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(reloadBtn))))
                    .addComponent(buscarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultBtn)
                    .addComponent(addBtn)
                    .addComponent(editBtn)
                    .addComponent(listadoBtn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int res = JOptionPane.showConfirmDialog(null, addEditPanel, "Registrar Paciente", JOptionPane.OK_CANCEL_OPTION);
        if(res == 0){
            try {
                razonVL.setVisible(true);
                addRazon.setVisible(true);
                String nom = addNom.getText();
                Paciente pac = PacienteControl.getPacienteNom(nom);
                if (pac == null){
                    int edad = Integer.parseInt(addEdad.getText());
                    String tel = addTel.getText();
                    pac = new Paciente(nom, edad, tel);
                    PacienteControl.savePaciente(pac);
                }
                Registro reg = new Registro(pac, addRazon.getText());
                Registro r = PacienteControl.saveRegistro(reg);
                initTable();
                JOptionPane.showMessageDialog(null, "¡Registro Añadido Exitosamente!\n"
                        + "Número de Identificación del Paciente: "+r.getIdPaciente().getId());
            } catch(Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void listadoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listadoBtnActionPerformed
        List<Expediente> exps = ExpControl.getExpedientes();
        List<Paciente> pacs = new ArrayList();
        String nomMed = ((RecepcionistaPersonal) mainFrame.getCurrUser()).getMedicoAsignado();
        for(Expediente ex: exps){
            if(ex.getMedico().getNombre().equals(nomMed)){
                pacs.add(ex.getPaciente());
            }
        }
        ContentChange.generarListado(pacs, nomMed);
    }//GEN-LAST:event_listadoBtnActionPerformed

    private void consultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultBtnActionPerformed
        try {
            int row = tablaRegistros.getSelectedRow();
            Long idPaciente = (Long) tablaRegistros.getValueAt(row, 0);
            Paciente pac = PacienteControl.getPacienteById(idPaciente);
            List<Registro> regs = PacienteControl.getRegistros(idPaciente);
            consulNom.setText(pac.getNombre());
            consulEdad.setText(String.valueOf(pac.getEdad()));
            consulTel.setText(pac.getTelefono());
            setVisitas(regs);
            JOptionPane.showMessageDialog(null, consultarPanel);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_consultBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        try {
            int row = tablaRegistros.getSelectedRow();
            Long idPaciente = (Long) tablaRegistros.getValueAt(row, 0);
            Paciente pac = PacienteControl.getPacienteById(idPaciente);
            addNom.setText(pac.getNombre());
            addEdad.setText(String.valueOf(pac.getEdad()));
            addTel.setText(pac.getTelefono());
            razonVL.setVisible(false);
            addRazon.setVisible(false);
            int res = JOptionPane.showConfirmDialog(null, addEditPanel, "Actualizar Datos Paciente", JOptionPane.OK_CANCEL_OPTION);
            if(res == 0){
                try {
                    String nom = addNom.getText();
                    int edad = Integer.parseInt(addEdad.getText());
                    String tel = addTel.getText();
                    pac.setNombre(nom);
                    pac.setEdad(edad);
                    pac.setTelefono(tel);
                    PacienteControl.updatePaciente(pac);
                    initTable();
                    JOptionPane.showMessageDialog(null, "¡Paciente Actualizado Exitosamente!");
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        initTable();
    }//GEN-LAST:event_reloadBtnActionPerformed
    
    private void initTable(){
        List<Paciente> pacs = PacienteControl.getPacientes();
        setTable(pacs);
    }
    
    private void setTable(List<Paciente> pacs){
        String[] tblH = {"Id", "Nombre", "Telefono"};
        DefaultTableModel model = new DefaultTableModel(tblH, 0);
        for(Paciente pac: pacs){
            Object[] row = {pac.getId(), pac.getNombre(), pac.getTelefono()};
            model.addRow(row);
        }
        tablaRegistros.setModel(model);
        tablaRegistros.setDefaultEditor(Object.class, null);
    }
    
    private void setVisitas(List<Registro> regs){
        String[] tblH = {"Razon de Visita", "Fecha", "Telefono"};
        DefaultTableModel model = new DefaultTableModel(tblH, 0);
        for(Registro reg: regs){
            Object[] row = {reg.getRazonVisita(), reg.getFecha()};
            model.addRow(row);
        }
        tablaVisitas.setModel(model);
        tablaVisitas.setDefaultEditor(Object.class, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addBuscarBtn;
    private javax.swing.JTextField addEdad;
    private javax.swing.JPanel addEditPanel;
    private javax.swing.JTextField addNom;
    private javax.swing.JTextField addRazon;
    private javax.swing.JTextField addTel;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton buscarBtn;
    private javax.swing.ButtonGroup busquedasBG;
    private javax.swing.JTextField consulEdad;
    private javax.swing.JTextField consulNom;
    private javax.swing.JTextField consulTel;
    private javax.swing.JButton consultBtn;
    private javax.swing.JPanel consultarPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JRadioButton idRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listadoBtn;
    private javax.swing.JRadioButton nomRB;
    private javax.swing.JLabel razonVL;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JTable tablaRegistros;
    private javax.swing.JTable tablaVisitas;
    // End of variables declaration//GEN-END:variables
}
