/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Keloc
 */
public class Principal extends javax.swing.JPanel {

    private String rol;
    public Principal(String rol) {
        this.rol = rol;
        initComponents();
        initStyles();
        initContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicoP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recepcionistaP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        recepcionistaPersonalP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<html>\n<p>Interfaz Principal de Medico</p>\n</html>");

        javax.swing.GroupLayout medicoPLayout = new javax.swing.GroupLayout(medicoP);
        medicoP.setLayout(medicoPLayout);
        medicoPLayout.setHorizontalGroup(
            medicoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicoPLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 310, Short.MAX_VALUE))
        );
        medicoPLayout.setVerticalGroup(
            medicoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicoPLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 135, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("<html> <p>Interfaz Principal de Recepcionista</p> </html>");

        javax.swing.GroupLayout recepcionistaPLayout = new javax.swing.GroupLayout(recepcionistaP);
        recepcionistaP.setLayout(recepcionistaPLayout);
        recepcionistaPLayout.setHorizontalGroup(
            recepcionistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionistaPLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 224, Short.MAX_VALUE))
        );
        recepcionistaPLayout.setVerticalGroup(
            recepcionistaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionistaPLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 147, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html> <p>Interfaz Principal de Recepcionista Personal</p> </html>");

        javax.swing.GroupLayout recepcionistaPersonalPLayout = new javax.swing.GroupLayout(recepcionistaPersonalP);
        recepcionistaPersonalP.setLayout(recepcionistaPersonalPLayout);
        recepcionistaPersonalPLayout.setHorizontalGroup(
            recepcionistaPersonalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionistaPersonalPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        recepcionistaPersonalPLayout.setVerticalGroup(
            recepcionistaPersonalPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recepcionistaPersonalPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(607, 347));
        setPreferredSize(new java.awt.Dimension(607, 347));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(607, 347));
        bg.setPreferredSize(new java.awt.Dimension(607, 347));
        bg.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Algo");
        bg.add(jLabel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initStyles(){
    }
    
    private void initContent(){
        System.out.println(rol);
        switch(rol){
            case "MEDICO":
                ContentChange.changePanel(bg, medicoP);
                medicoP.setVisible(true);
                break;
            case "RECEPCIONISTA":
                ContentChange.changePanel(bg, recepcionistaP);
                recepcionistaP.setVisible(true);
                break;
            case "RECEPCIONISTA PERSONAL":
                ContentChange.changePanel(bg, recepcionistaPersonalP);
                recepcionistaPersonalP.setVisible(true);
                break;
            default:
                break;
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel medicoP;
    private javax.swing.JPanel recepcionistaP;
    private javax.swing.JPanel recepcionistaPersonalP;
    // End of variables declaration//GEN-END:variables
}
